### ISSUE TITLE
Add an initial check if users have completed the site verification

### ISSUE THREAD

**Issue by Ashesh3** [0x25CBFC4F/SteamAccChanger#1]
Starting from yesterday, api usage requires users to perform a one time verification for their IP to be allowed to use the API.

Whenever they try to generate an account,
(Add this before you even check the stats)
Add a check when, the response is 
```
{"success":0,"error":"Verification pending, go to http://accgen.undo.it/ to finish it"}
```
Then just tell users to go to the url once, after they go to the url, they'll be presented by a one time verification, after that API will start working normally.

https://github.com/0x25CBFC4F/SteamAccChanger/blob/4bfe83524ea4ddd9248ebeb9547f60ee4b2690d5/SteamAccChanger/Utils.cs#L51

Just before that part of checking limitations, maybe add a small check for this verification response.

**Comment by 0x25CBFC4F** [comment]
Gonna fix.

**Comment by 0x25CBFC4F** [comment]
Fixed in https://github.com/0x25CBFC4F/SteamAccChanger/commit/f09a6f0f68ad8d106287379932e6650412beb05f commit.
